services:
  studiaapp:
    image: studiaapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - APP_PORT=3000

      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=studiadb
      - DB_USER=node
      - DB_PASSWORD=node123
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - database.env
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
